development:
  cloud_name: dv83rzhxv
  api_key: '161511945215219'
  api_secret: uGJ-lDXxzJVX0JEEbdRnoAD2Mk8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dv83rzhxv
  api_key: '161511945215219'
  api_secret: uGJ-lDXxzJVX0JEEbdRnoAD2Mk8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dv83rzhxv
  api_key: '161511945215219'
  api_secret: uGJ-lDXxzJVX0JEEbdRnoAD2Mk8
  enhance_image_tag: true
  static_image_support: false
